spring.application.name=exercise02
server.port=8082

# ======================
# = MySQL (Persons & Events)
# ======================
spring.datasource.url=jdbc:mysql://localhost:3306/agenda_amigos?serverTimezone=GMT-3
spring.datasource.username=agenda_amigos
spring.datasource.password=agenda123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.transaction-manager=jpaTransactionManager
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ======================
# = MongoDB (Hobbies)
# ======================
spring.data.mongodb.uri=mongodb://localhost:27017/agenda
# ======================
# = Neo4j (Friends)
# ======================
spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=neo4j1234


